name: Push Main Branches

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  # Publish docker image in Github Container Registry to application
    # Build dist application ADVue-Theme-Pos
  build-app:
    name: Build dist ADVue-Theme-Pos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: 'zip'
          filename: 'ADVue-Theme-Pos.zip'
          path: './'
          exclusions: './dist ./docker ./docs'

      - name: Upload app as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ADVue-Theme-Pos        
          path: ./ADVue-Theme-Pos.zip


  # Publish docker image in Github Container Registry to application
  push-imame-ghcr:
    name: Push Docker image to GitHub Container
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download build dist app
        uses: actions/download-artifact@v2
        with:
          name: ADVue-Theme-Pos

      - name: Uncompress dist files
        run: unzip ADVue-Theme-Pos.zip -d dist-app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Lower Case to owner and repository
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
          echo "REPO_LC=${NAME,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          NAME: '${{ github.event.repository.name }}'

      # - name: Get branch name
      #   id: branch-name
      #   uses: tj-actions/branch-names@v4.8

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ steps.branch-name.outputs.current_branch }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # Publish docker image in Digital Ocean registry to application
  # push-imame-ddor:
  #   name: Push Docker image to Digital Ocean
  #   needs:
  #     - build-app
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2

  #     - name: Download build dist app
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ADVue-Theme-Pos

  #     - name: Uncompress dist files
  #       run: unzip ADVue-Theme-Pos.zip -d dist-app

  #     - name: Get branch name
  #       id: branch-name
  #       uses: tj-actions/branch-names@v4.8

  #     - name: Build image
  #       run: docker build -t ADVue-Theme-Pos -f build/Dockerfile .

  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  #     - name: Log in to DO Container Registry
  #       run: doctl registry login --expiry-seconds 600
  #     - name: Tag image
  #       run:
  #         docker tag ADVue-Theme-Pos registry.digitalocean.com/erpya/ADVue-Theme-Pos:${{ github.ref }}
  #     - name: Push image to DO Container Registry
  #       run: docker push registry.digitalocean.com/erpya/ADVue-Theme-Pos:${{ github.ref }}
