name: Push Main Branches

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  # Publish docker image in Github Container Registry to application
    # Build dist application ADVue-Theme-Pos
  build-app:
    name: Build dist ADVue-Theme-Pos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: 'zip'
          filename: 'ADVue-Theme-Pos.zip'
          path: './'
          exclusions: './dist ./docker ./docs'

      - name: Upload app as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ADVue-Theme-Pos        
          path: ./ADVue-Theme-Pos.zip
